const data = {
    0: {
        color: 'rgb(47,118,147)',
<<<<<<< HEAD
        classNames: '',
        contentID: 'GqudDMIPQCk',
        title: 'Cars 2',
        describtion: 'Cars',
=======
        classNames: 'lichterkette',
        contentID: '',
        title: '',
        describtion: '',
>>>>>>> 2b544e73edd160648f7ccb1b72ebf2f3e8c7c5bd
    },
    1: {
        color: 'rgb(112,128,131)',
        classNames: '',
        contentID: 'LDU_Txk06tM',
        title: 'Crab Rave test',
        describtion: '',
    },
    2: {
        color: 'rgb(60,109,201)',
        classNames: '',
        contentID: 'Zryz0fQoI3I',
        title: 'Peter Pan',
        describtion: 'Peter Pan',
    },
    3: {
        color: 'rgb(227,233,238)',
        classNames: 'adventskranz2',
        contentID: 'zv_u2bpAxGE',
        title: 'Sally Bollywood',
        describtion: 'Sally Bollywood',
    },
    4: {
        color: 'rgb(9, 94, 173)',
        classNames: '',
        contentID: 'pIlFsxGzN_0',
        title: 'Shameless',
        describtion: 'Shameless',
    },
    5: {
        color: 'rgb(3, 82, 255)',
        classNames: 'nikolaus',
        contentID: 'Yduo1lN7fAI',
        title: 'Elite',
        describtion: 'Elite',
    },
    6: {
        color: 'rgb(95, 90, 199)',
        classNames: 'ngW2mOhysfc',
        contentID: 'ngW2mOhysfc',
        title: 'Peaky Blinders',
        describtion: 'Peaky Blinders',
    },
    7: {
        color: 'rgb(98, 124, 188)',
        classNames: '',
        contentID: '0z_WwoRHHUc',
        title: 'Barbie the Island Princess',
        describtion: 'Barbie the Island Princess',
    },
    8: {
        color: 'rgb(47,118,147)',
        classNames: '',
        contentID: 'rYJ6bg0NCII',
        title: 'Spider Man Miles Morales',
        describtion: 'Spider Man Miles Morales',
    },
    9: {
        color: 'rgb(112,128,131)',
        classNames: '',
        contentID: '6zbdyyV1lok',
        title: 'Cars 3',
        describtion: 'Cars 3',
    },
    //Peschl
    10: {
        color: 'rgb(60,109,201)',
        classNames: 'adventskranz3',
        contentID: 'cUVdityDkJM',
        title: 'Kevin - Allein in New York',
        describtion: 'Kevin wird vo sina Familie in New York vergeassa des Opfa',
    },
    11: {
        color: 'rgb(227,233,238)',
        classNames: '',
        contentID: 'ajXAwMB8eR0',
        title: 'Alice in Borderland',
        describtion: 'Alice in Borderland',
    },
    12: {
        color: 'rgb(9, 94, 173)',
        classNames: '',
        contentID: 'D-SPRCQAb9E',
        title: 'Bojack Horesmam',
        describtion: 'irgendan komischa Pferdemann',
    },
    13: {
        color: 'rgb(3, 82, 255)',
        classNames: '',
        contentID: '-JtwROpSVWc',
        title: 'The Knight before Christmas',
        describtion: 'The Knight before Christmas',
    },
    14: {
        color: 'rgb(95, 90, 199)',
        classNames: '',
        contentID: 'JPFl5HLljl8',
        title: 'Prinzessinnentausch',
        describtion: 'Prinzessinnentausch',
    },
    15: {
        color: 'rgb(98, 124, 188)',
        classNames: '',
        contentID: '',
        title: '',
        describtion: '',
    },
    16: {
        color: 'rgb(47,118,147)',
        classNames: '',
        contentID: '',
        title: '',
        describtion: '',
    },
    17: {
        color: 'rgb(112,128,131)',
        classNames: 'adventskranz4',
        contentID: '',
        title: '',
        describtion: '',
    },
    18: {
        color: 'rgb(60,109,201)',
        classNames: '',
        contentID: '',
        title: '',
        describtion: '',
    },
    19: {
        color: 'rgb(227,233,238)',
        classNames: '',
        contentID: '',
        title: '',
        describtion: '',
    },
    20: {
        color: 'rgb(9, 94, 173)',
        classNames: '',
        contentID: '',
        title: '',
        describtion: '',
    },
    21: {
        color: 'rgb(3, 82, 255)',
        classNames: '',
        contentID: '',
        title: '',
        describtion: '',
    },
    22: {
        color: 'rgb(95, 90, 199)',
        classNames: '',
        contentID: '',
        title: '',
        describtion: '',
    },
    23: {
        color: 'rgb(98, 124, 188)',
        classNames: 'weihnachten',
        contentID: '',
        title: '',
        describtion: '',
    },

    //weihnachten und nikolaus sind nur temporär und kann ma spöter no ändern!!!!!!!
};

// const doorConfig = {
//     0: { contentID: '' },
//     1: {
//         contentID: 'LDU_Txk06tM',
//         title: 'Crab Rave test',
//         describtion: 'test',
//     },
//     2: { contentID: '' },
//     3: { contentID: '' },
//     4: { contentID: '' },
//     5: { contentID: '' },
//     6: { contentID: '' },
//     7: { contentID: '' },
//     8: { contentID: '' },
//     9: { contentID: '' },
//     10: { contentID: '' },
//     11: { contentID: '' },
//     12: { contentID: '' },
//     13: { contentID: '' },
//     14: { contentID: '' },
//     15: { contentID: '' },
//     16: { contentID: '' },
//     17: { contentID: '' },
//     18: { contentID: '' },
//     19: { contentID: '' },
//     20: { contentID: '' },
//     21: { contentID: '' },
//     22: { contentID: '' },
//     23: { contentID: '' },
// };